# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: windows-agent-sonal

parameters:
- name: run_apply
  displayName: Selection of apply command
  type: boolean
  default: true
  values:
    - true
    - false

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)\env\dev'
    backendServiceArm: 'asr'
    backendAzureRmResourceGroupName: 'for-backend'
    backendAzureRmStorageAccountName: 'pipelinekeliye'
    backendAzureRmContainerName: 'pipestorage'
    backendAzureRmKey: 'dev11.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)\env\dev'
    environmentServiceNameAzureRM: 'asr'

- task: TerraformTask@5
  condition: and(succeeded(), ${{ parameters.run_apply }})
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)\env\dev'
    environmentServiceNameAzureRM: 'asr'