# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: windows-agent-sonal

parameters:
- name: run_apply
  displayName: Selection of apply command
  type: boolean
  default: false
  values:
    - true
    - false

stages:
- stage: init_plan_stage
  jobs:
  - job: init_plan
    displayName: init_and_plan
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\env\dev'
        backendServiceArm: 'asr'
        backendAzureRmResourceGroupName: 'for-backend'
        backendAzureRmStorageAccountName: 'pipelinekeliye'
        backendAzureRmContainerName: 'pipestorage'
        backendAzureRmKey: 'dev1122.tfstate'
    
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)\env\dev'
        environmentServiceNameAzureRM: 'asr'

- stage: apply_stage
  jobs:
  - job: apply_wala
    condition: and(succeeded(), ${{ parameters.run_apply }})
    displayName: apply_stage
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\env\dev'
        backendServiceArm: 'asr'
        backendAzureRmResourceGroupName: 'for-backend'
        backendAzureRmStorageAccountName: 'pipelinekeliye'
        backendAzureRmContainerName: 'pipestorage'
        backendAzureRmKey: 'dev1122.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)\env\dev'
        environmentServiceNameAzureRM: 'asr'
